### ISSUE TITLE
Покупки должны храниться в массиве

### ISSUE THREAD

**Issue by coursar** [Islomzoda/cashbackcart#2]
https://github.com/Islomzoda/cashbackcart/blob/be3b34ab183fabe4b0104680b3796b936ad19a74/src/js/app.js#L1-L14

<img width="662" alt="Снимок экрана 2020-01-11 в 17 09 37" src="https://user-images.githubusercontent.com/3601892/72204209-35783d80-3497-11ea-88cd-fe9f3d48fa77.png">

**Comment by Islomzoda** [comment]
добавил в масив
